Faq
AY2425S1-CS2103T-T10-1/tp pull request #276
Opened 2024-11-10 12:18 UTC by LynetteLeeSiYing

**Main Changes**
1. Edit Quick Start
2. Include target audience in introduction
3. Update FAQ

close #254

2024-11-10 14:23 UTC, OttoTan approved these changes
LGTM

2024-11-10 15:41 UTC, myrilla12 reviewed
Looks good! Just a few small suggestions.

2024-11-10 15:41 UTC, myrilla12 commented on docs/UserGuide.md
> +**A**: Check out [Features](#features) or simple run `help` to see the full list of commands, and try entering a valid command again.
Small typo, can consider replacing 'simple' with 'simply'

2024-11-10 15:41 UTC, myrilla12 commented on docs/UserGuide.md
> +**Q**: Can I mark certain patients as high-priority?<br>
Can consider rewording this question to marking patients as 'favourite' or 'more important` instead. High-priority could potentially imply that there's a feature allowing them to set patient contacts as low, medium or high priority.

2024-11-10 15:41 UTC, myrilla12 commented on docs/UserGuide.md
> +| **Delete** | `delete INDEX` or `delete NAME` <br> e.g., `delete 3`, `delete Alex Yeoh`
Can consider removing the `.` after the `e.g` in this table. Seems unnecessary.

2024-11-11 02:10 UTC, Bonzzz3 requested changes
LGTM, just that the Ui doesn't adhere to requirement. Can just delete the Ui and lmk which part of the current Ui you would like me to change.

2024-11-11 02:10 UTC, Bonzzz3 commented on docs/images/Ui.png
Ui seems a bit too small for me and I think it should show at least 2/3 full contacts. Also the bottom part is cut off. Perhaps you can state what is the problem with the current Ui and I can change it later.
![image](https://github.com/user-attachments/assets/0a8a3410-a16a-4a66-ae4b-43204f08be7f)

2024-11-11 12:01 UTC, ritvi12 approved these changes
LGTM!

2024-11-11 12:02 UTC, Bonzzz3 approved these changes

2024-11-11 12:02 UTC, merged