Find contact
AY2425S1-CS2103T-T10-1/tp pull request #55
Opened 2024-10-14 09:57 UTC by LynetteLeeSiYing

- Match partial keyword with name or phone number
- Update user guide for find command

close #54

2024-10-14 10:22 UTC, ritvi12 requested changes
Other than the changes to the command structure everything else looks good to me.

2024-10-14 10:22 UTC, ritvi12 commented on docs/images/findOlive.png
Is the purpose of find to be able to find strings from two different contacts in the same command? Maybe can change it to be able to find either name or phone but one at a time or both from the same contact, not two different contacts.

2024-10-14 10:36 UTC, Bonzzz3 commented on docs/images/findOlive.png
In the original AB3, the find command can search for multiple keywords and list anything that matches either keywords. Maybe we could highlight this feature in the user guide for users because I feel like finding multiple keywords are better than one. Just my opinion though :)

2024-10-14 10:37 UTC, Bonzzz3 approved these changes
LGTM

2024-10-15 13:09 UTC, ritvi12 approved these changes

2024-10-15 13:09 UTC, merged